trainingInput:
  scaleTier: CUSTOM
  #masterType: n1-highcpu-32
  #scaleTier: STANDARD_1
  #masterType: n1-highcpu-16
  masterType: n2-standard-4
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: "reward"
    maxTrials: 4
    maxParallelTrials: 4
    enableTrialEarlyStopping: True
    params:
    #- parameterName: behaviors-RollerBall-hyperparameters-learning_rate
    #  type: DOUBLE
    #  minValue: 2.5e-4
    #  maxValue: 3.5e-4
    #- parameterName: behaviors-RollerBall-reward_signals-extrinsic-gamma
    #  type: DOUBLE
    #  minValue: 0.95
    #  maxValue: 0.999
    #- parameterName: behaviors-RollerBall-network_settings-hidden_units
    #  type: INTEGER
    #  minValue: 128
    #  maxValue: 256
    #- parameterName: behaviors-RollerBall-hyperparameters-batch_size
    #  type: DISCRETE
    #  discreteValues:
    #    - 10
    #    - 20
    #    - 50
    - parameterName: behaviors-RollerBall-hyperparameters-beta
      type: DISCRETE
      discreteValues:
        - 0.0005
        - 0.005
        - 0.05
        - 0.5
    #- parameterName: behaviors-RollerBall-max_steps
    #  type: DISCRETE
    #  discreteValues:
    #    - 200000
    #    - 400000
    #    - 800000
    #- parameterName: behaviors-RollerBall-hyperparameters-learning_rate_schedule
    #  type: CATEGORICAL
    #  categoricalValues:
    #    - linear
    #    - constant
